name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          script-stop: true
          script: |
            cd /home/ubuntu/instagram-server
            git pull origin main
            ./gradlew clean build
            nohup java -jar .build/libs/*SNAPSHOT.jar > ./nohup2.log 2>&1 &
            
