name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기 3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script-stop: true
          script: |
            cd /home/ubuntu/instagram-server
            git pull origin main
            sudo chmod +x gradlew
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar ./build/libs/*SNAPSHOT.jar > ./nohup2.log 2>&1 &
            
